apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${APP_NAME}
  labels:
    app: ${APP_NAME}
spec:
  selector:
    matchLabels:
      app: ${APP_NAME}
  replicas: ${REPLICAS}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ${APP_NAME}
        group: ${LABEL_GROUP}
    spec:
      containers:
      - name: ${APP_NAME}
        image: ${IMAGE_URL}
        imagePullPolicy: ${IMAGE_PULL_POLICY}
        ports:
        - containerPort: ${CONTAINER_PORT}
        resources:
            requests:
              cpu: ${CPU_REQUEST}
              memory: ${MEMORY_REQUEST}
            limits:
              cpu: ${CPU_LIMIT}
              memory: ${MEMORY_LIMIT}
        env:
        - name: PYTHONPATH
          value: "src"





