name: Manual Trigger
on:
  workflow_dispatch:
    inputs:
      workspaceId:
        description: Workspace Id (Changes tfstate bucket)    
        default: testing
        type: choice
        options:
        - Testing
        - Staging
        - Production-1
        - Production-2
        - Leia-Renee
      targetAwsAccountId:
        description: Target AWS Account Id   
        default: 553688522943
        type: choice
        options:
        - 553688522943 # testing
        - 518854297938 # Staging
        - 009403416359 # Prod1
        - 230794785515 # Prod2
        - 684353670650 # Dev Leia
      targetAwsRegion:
        description: Target AWS Region     
        default: eu-west-1
        type: choice
        options:
        - eu-central-1
        - eu-west-1
        - eu-west-2
        - eu-west-3
        - eu-south-1
        - eu-north-1
        - us-east-1
        - us-east-2
        - us-west-1
        - us-west-2
      runAll:
        description: Terragrunt run-all
        default: true 
        type: boolean
      tgCommand: 
        description: Terragrunt command
        default: apply
        type: choice
        options:
        - validate
        - plan
        - apply
        - destroy
        - show
        - output
      tgArguments:
        description: TG Cli arguments
      stackFolder:
        description: Main Stack Folder
        default: live
        type: choice
        options:
        - live
        - test
      runModule:
        description: Terragrunt Module Folder - Choose from https://github.com/leiarenee/sf-infra/tree/main/infra/live
        default:
      ttlDuration:
        description: Time to Live in minutes 
        default: 30

jobs:
  terragrunt-validate-build-test:
    uses: leiarenee/sf-pipeline/.github/workflows/execute-sf.yml@deploy
    with:
      workspaceId: ${{ inputs.workspaceId }}
      targetAwsAccountId: ${{ inputs.targetAwsAccountId }}
      targetAwsRegion: ${{ inputs.targetAwsRegion }}
      runAll: ${{ inputs.runAll }}
      tgCommand: ${{ inputs.tgCommand }}
      tgArguments: ${{ inputs.tgArguments }}
      stackFolder: ${{ inputs.stackFolder }}
      runModule: ${{ inputs.runModule }}
      ttlDuration: ${{ inputs.ttlDuration }}
      repoReference: ${{ github.ref }}
    secrets: inherit
  



